### ISSUE TITLE
App crashes on running [CleverTap autoIntegrate], method swizzling issue (v3.2.1 and v3.2.2 iOS11 and 12)

### ISSUE THREAD

**Issue by shubham-mandal** [CleverTap/clevertap-ios-sdk#15]
![clevertap_crash](https://user-images.githubusercontent.com/33017988/47480352-becd3100-d84d-11e8-9eb9-763edb7cebe2.png)

**Comment by shubham-mandal** [comment]
I followed the doc provided. 
1> added pod **(pod "CleverTap-iOS-SDK")** and **pod install**
2>CleverTapAccountID and CleverTapToken added to the plist files.
3> In the Appdelegate called **autoIntegrate**
When I run on the device to debug the app, the app crashes. Is it something like CleverTap won't work on Sandbox mode?

**Comment by Aditi3** [comment]
Nothing like that CleverTap doesn't work on Sandbox mode. 

Try enabling the debug mode, following code snippet will be useful

```
#ifdef DEBUG
   [CleverTap setDebugLevel:CleverTapLogDebug];
#else
   [CleverTap setDebugLevel:CleverTapLogOff];
#endif
```
Please share the log, will helps us in investigating more on this.

**Comment by shubham-mandal** [comment]
Is there a way to possibly connect with you on a different medium. I have been debugging the classes CTSwizzle and CleverTap, and it seems to have some issue with OneSignal. Attaching the screenshots for the same. 
Class CleverTap is not able to swizzle **userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler**.  The **Method** var is null, hence the method signature gives a crash.
**Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[NSMethodSignature signatureWithObjCTypes:]: type signature is NULL.'** 

![first](https://user-images.githubusercontent.com/33017988/47487612-64899b80-d860-11e8-985c-99e1f3d8d703.png)
![second](https://user-images.githubusercontent.com/33017988/47487629-69e6e600-d860-11e8-8aa1-f4eee4653459.png)
![third](https://user-images.githubusercontent.com/33017988/47487648-71a68a80-d860-11e8-8aef-177bed4f5f97.png)

Kindly help me proceed.

**Comment by Aditi3** [comment]
Hey @shubham-mandal 

Would request you to write to support@clevertap.com to take the discussion forward.

Thanks!

**Comment by shubham-mandal** [comment]
I will do that in a parallel thread. Meanwhile, please help me out with this.

**Comment by rajivnarayana** [comment]
There is an issue when integrated with Firebase also. Or any other framework or even with no framework. The crash can be reproduced If there is an `UNNotificationCenterDelegate` which implements `userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler` when `[CleverTap autoIntegrate]` gets called.

A mistake can be clearly spotted in the following code from [CleverTap swizzleAppDelegate], also seen in the screenshot above from @shubham-mandal 
```Objc
class_getInstanceMethod(ncdCls, NSSelectorFromString(@"userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:"))) {
                sel = NSSelectorFromString(@"userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:");
                __block NSInvocation *invocation = nil;
invocation = [cls ct_swizzleMethod:sel withBlock:^(id obj, UNUserNotificationCenter *center, UNNotificationResponse *response, void (^completion)(UIBackgroundFetchResult result) ) {
```
`ncdCls` should be swizzled and not `cls`. Could have occurred during copy paste from other methods swizzled.

**Comment by Aditi3** [comment]
Thank you @rajivnarayana for pointing this out. We too have noticed it and added a fixed in the version 3.4.1.

Sorry for the inconvenience caused.

**Comment by j1mmyto9** [comment]
> Thank you @rajivnarayana for pointing this out. We too have noticed it and added a fixed in the version 3.4.1.
> 
> Sorry for the inconvenience caused.

Hi all. I still face this issue with the latest version -  `CleverTap-iOS-SDK (4.2.0)`.
My app already has `onesignal`, and now i want to integrate Clevertap also. But seem not able to use both in the project. the Project just run after I disabled one of them.

<img width="1290" alt="Screenshot 2023-01-17 at 12 45 25" src="https://user-images.githubusercontent.com/9074095/212819404-2bcb1f4d-0929-4d85-bcac-89c51458730f.png">

**Comment by niteshmain** [comment]
@j1mmyto9 I'm running into a similar issue. I'm trying to integrate CleverTap into my app that already has Firebase. Activating both of these SDKs causes the same crash from your screenshot. 

Did you ever find a solution for your issue?
